#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# CHANGE THIS BEFORE LAUNCHING ON A DIFFERENT SETUP
bspc monitor HDMI-1 -d 1 2 3 4 5
bspc monitor DP-1 -d 6 7 8 9 10

bspc config border_width          3
bspc config window_gap            7
bspc config -m DP-1 top_padding   0
bspc config -m HDMI-1 top_padding 26

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config click_to_focus button1

# custom color sources
# Special
background='#0a090a'
foreground='#dee1e3'
cursor='#dee1e3'

# Colors
color0='#84B8CD'
color1='#3CE5D8'
color2='#A39DA7'
color3='#DFA7AA'
color4='#84B8CD'

bspc config normal_border_color \#9ba5eb
bspc config active_border_color \#c0caf5
bspc config focused_border_color \#c0caf5

# launch commands
feh --bg-fill ~/wallpapers/wallpaper.png & # set wallpaper

# PERFORMANCE HEAVY - COMMENT OUT IF PERFORMANCE IS PREFERRED
picom --config ~/.config/picom/picom.conf & # launch picom
conky -c ~/.config/conky/conky.conf & # launch conky clock
conky -c ~/.config/conky/conky2.conf & # launch conky todo list
~/.config/polybar/launch.sh & # top bar launch script
